name: Automatically create maps

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'oracle'
    - name: Build with Ant
      run: ant jar
    - name: Make endless-sky directory
      run: mkdir endless-sky
    - name: Download ES files
      uses: actions/checkout@v6
      with:
        repository: 'endless-sky/endless-sky'
        path: endless-sky
    - name: Run Program
      run: java -jar "ES Mapper.jar" "default config.txt"
    - name: list files
      run: ls
    - name: Remove unneeded files
      run: |
        rm -r endless-sky
    - name: Commit map files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add . -f
        git add bin
        git commit -m "Map Creation"
    - name: Push map files
      uses: ad-m/github-push-action@v1.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: maps
        force: true
        # rm .gitignore
        # rm -r .github/
        # rm "ES Mapper.jar"
        # rm LICENSE
        # rm README.md
        # rm -r assets
        # rm build.xml
        # rm "default config.txt"
        # rm -r src
