name: Automatically create maps

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'oracle'
    - name: Build with Ant
      run: ant jar
    - name: Make endless-sky directory
      run: mkdir endless-sky
    - name: Download ES files
      uses: actions/checkout@v4
      with:
        repository: 'endless-sky/endless-sky'
        path: endless-sky
    - name: List folder contents
      run: ls
    - name: Run Program
      run: java -jar "ES Mapper.jar" "default config.txt"
